Document: graphite-integration
Title: Debian graphite-integration Manual
Author: <insert document author here>
Abstract: This manual describes what graphite-integration is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/graphite-integration/graphite-integration.sgml.gz

Format: postscript
Files: /usr/share/doc/graphite-integration/graphite-integration.ps.gz

Format: text
Files: /usr/share/doc/graphite-integration/graphite-integration.text.gz

Format: HTML
Index: /usr/share/doc/graphite-integration/html/index.html
Files: /usr/share/doc/graphite-integration/html/*.html
